fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
    powershell: "git://github.com/joshcooper/puppetlabs-powershell.git"
  symlinks:
    windows_certs: "#{source_dir}"
